# Generated by Django 5.2.17 on 2026-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("descricao", models.TextField()),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
