# Generated by Django 5.2.17 on 2026-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("capacidade", models.IntegerField()),
                (
                    "localizacao",
                    models.CharField(
                        choices=[
                            ("salao", "Salao interno"),
                            ("varanda", "Varanda"),
                            ("externa", "Area externa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
    ]
